students/21K0637/21K0637-p09/pom.xml, students/21K0637/21K0637-p09/src/main/java/ru/mirea/practice/task1/Sorting.java, students/21K0637/21K0637-p09/src/main/java/ru/mirea/practice/task1/Student.java, students/21K0637/21K0637-p09/src/main/java/ru/mirea/practice/task2/Sorting.java, students/21K0637/21K0637-p09/src/main/java/ru/mirea/practice/task2/Student.java, students/21K0637/21K0637-p09/src/main/java/ru/mirea/practice/task3/MergeSort.java, students/21K0637/21K0637-p10/pom.xml, students/21K0637/21K0637-p10/src/main/java/ru/mirea/practice/Main.java, students/21K0637/21K0637-p10/src/main/java/ru/mirea/practice/MergeArrays.java, students/21K0637/21K0637-p10/src/main/java/ru/mirea/practice/SortingStudentByGpa.java, students/21K0637/21K0637-p10/src/main/java/ru/mirea/practice/Student.java, students/21K0637/pom.xml
=> Добавлены 9-10 практические

pom.xml, students/21K0664/21K0664-p04.1/src/main/java/ru/mirea/workfourone/task10/Airplane.java, students/21K0664/21K0664-p04.1/src/main/java/ru/mirea/workfourone/task10/Car.java, students/21K0664/21K0664-p04.1/src/main/java/ru/mirea/workfourone/task10/Ship.java, students/21K0664/21K0664-p04.1/src/main/java/ru/mirea/workfourone/task10/Test.java, students/21K0664/21K0664-p04.1/src/main/java/ru/mirea/workfourone/task10/Train.java, students/21K0664/21K0664-p04.1/src/main/java/ru/mirea/workfourone/task10/Vehicle.java, students/21K0664/21K0664-p04.1/src/main/java/ru/mirea/workfourone/task9/Bed.java, students/21K0664/21K0664-p04.1/src/main/java/ru/mirea/workfourone/task9/Chair.java, students/21K0664/21K0664-p04.1/src/main/java/ru/mirea/workfourone/task9/Furniture.java, students/21K0664/21K0664-p19/pom.xml, students/21K0664/21K0664-p19/src/main/java/ru/mirea/worknineteen/Main.java, students/21K0664/21K0664-p19/src/main/java/ru/mirea/worknineteen/task1/BadInn.java, students/21K0664/21K0664-p19/src/main/java/ru/mirea/worknineteen/task1/Student.java, students/21K0664/21K0664-p19/src/main/java/ru/mirea/worknineteen/task1/Test.java, students/21K0664/21K0664-p19/src/main/java/ru/mirea/worknineteen/task2/SortBygpa.java, students/21K0664/21K0664-p19/src/main/java/ru/mirea/worknineteen/task2/Student.java, students/21K0664/21K0664-p19/src/main/java/ru/mirea/worknineteen/task2/StudentError.java, students/21K0664/21K0664-p19/src/main/java/ru/mirea/worknineteen/task2/Test.java, students/21K0664/21K0664-p20/pom.xml, students/21K0664/21K0664-p20/src/main/java/ru/mirea/workeightteen/Main.java, students/21K0664/21K0664-p22/pom.xml, students/21K0664/21K0664-p22/src/main/java/ru/mirea/workeightteen/Main.java, students/21K0664/21K0664-p23/pom.xml, students/21K0664/21K0664-p23/src/main/java/ru/mirea/workeightteen/Main.java, students/21K0664/21K0664-p24/pom.xml, students/21K0664/21K0664-p24/src/main/java/ru/mirea/workeightteen/Main.java, students/21K0664/pom.xml
Микитенко Иван. КВБО-02-21. 21К0664
=> Проверьте пожалуйста 3 - 19 практические работы

pom.xml, students/21K0597/21K0597-p01/pom.xml, students/21K0597/21K0597-p01/src/main/java/ru/mirea/practice/Task1.java, students/21K0597/21K0597-p01/src/main/java/ru/mirea/practice/Task2.java, students/21K0597/21K0597-p01/src/main/java/ru/mirea/practice/Task3.java, students/21K0597/21K0597-p01/src/main/java/ru/mirea/practice/Task4.java, students/21K0597/21K0597-p01/src/main/java/ru/mirea/practice/Task5.java, students/21K0597/21K0597-p02/pom.xml, students/21K0597/pom.xml
На проверку - практическая работа 1
=> Практическая работа №1

students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task1/Author.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task1/TestAuthor.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task10/HowMany.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task2/Ball.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task2/TesterBall.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task3/Circle.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task3/Main.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task3/Point.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task3/Tester.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task4/Computer.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task4/Shop.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task4/Test.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task5/Dog.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task5/Kennel.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task5/Test.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task6/Circle.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task6/CircleTest.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task6/Point.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task7/Book.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task7/BookTest.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task7/Bookshelf.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task8/Swap.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task9/Deck.java, students/21K0689/21K0689-p02/src/main/java/ru/mirea/practice/task9/Poker.java
Проверьте, пожалуйста, вторую практическую работу
=> Вторая практическая работа

students/21K0664/21K0664-p07/src/main/java/ru/mirea/workseven/task78/Magazines.java, students/21K0664/21K0664-p08/src/main/java/wokreight/MainTest.java, students/21K0664/21K0664-p14/src/main/java/ru/mirea/workfourteen/task4/Numbers.java, students/21K0664/21K0664-p25/src/main/java/ru/mirea/worktwentyfive/task1/Str.java, students/21K0664/21K0664-p25/src/main/java/ru/mirea/worktwentyfive/task2/Stroke.java, students/21K0664/21K0664-p25/src/main/java/ru/mirea/worktwentyfive/task3/Money.java, students/21K0664/21K0664-p25/src/main/java/ru/mirea/worktwentyfive/task4/Numbers.java, students/21K0664/21K0664-p25/src/main/java/ru/mirea/worktwentyfive/task5/Birthday.java, students/21K0664/21K0664-p25/src/main/java/ru/mirea/worktwentyfive/task6/Mail.java, students/21K0664/21K0664-p25/src/main/java/ru/mirea/worktwentyfive/task7/Password.java, students/21K0664/21K0664-p26/src/main/java/ru/mirea/worktwentysix/task1/Test.java, students/21K0664/21K0664-p26/src/main/java/ru/mirea/worktwentysix/task23/Iterators.java, students/21K0664/21K0664-p26/src/main/java/ru/mirea/worktwentysix/task23/MyIterator.java, students/21K0664/21K0664-p27/src/main/java/ru/mirea/worktwentyseven/Main.java, students/21K0664/21K0664-p27/src/main/java/ru/mirea/worktwentyseven/task1/HashTab.java, students/21K0664/21K0664-p27/src/main/java/ru/mirea/worktwentyseven/task1/Node.java, students/21K0664/21K0664-p27/src/main/java/ru/mirea/worktwentyseven/task1/Test.java, students/21K0664/21K0664-p28/src/main/java/ru/mirea/worktwentyeight/Main.java, students/21K0664/21K0664-p28/src/main/java/ru/mirea/worktwentyeight/task1/Test.java, students/21K0664/21K0664-p28/src/main/java/ru/mirea/worktwentyeight/task2/Test.java, students/21K0664/21K0664-p28/src/main/java/ru/mirea/worktwentyeight/task3/Test.java, students/21K0664/pom.xml
Добавил 25,26,27,28 практические работы
=> Практическая работа Микитенко Ивана

students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task1/s21k0627/Author.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task1/s21k0627/TestAuthor.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task10/s21k0627/HowMany.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task2/s21k0627/Ball.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task2/s21k0627/TestBall.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task3/s21k0627/Circle.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task3/s21k0627/Point.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task3/s21k0627/Tester.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task4/s21k0627/Computer.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task4/s21k0627/Shop.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task5/s21k0627/Dog.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task5/s21k0627/DogHouse.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task6/s21k0627/Circle.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task6/s21k0627/TestCircle.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task7/s21k0627/Book.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task7/s21k0627/BookShelf.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task7/s21k0627/BookTest.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task8/s21k0627/SwapString.java, students/21K0627/21K0627-p02/src/main/java/ru/mirea/practice/task9/s21k0627/Poker.java
Проверьте пожалуйста 2 практическую работу Квашниной Дарьи КВБО-03-21
=> 2 практическая работа

students/21K0689/21K0689-p03/pom.xml, students/21K0689/21K0689-p03/src/main/java/ru/mirea/practice/task1/Array.java, students/21K0689/21K0689-p03/src/main/java/ru/mirea/practice/task2/Circle.java, students/21K0689/21K0689-p03/src/main/java/ru/mirea/practice/task2/Main.java, students/21K0689/21K0689-p03/src/main/java/ru/mirea/practice/task2/Point.java, students/21K0689/21K0689-p03/src/main/java/ru/mirea/practice/task2/Tester.java, students/21K0689/21K0689-p03/src/main/java/ru/mirea/practice/task3/Array.java, students/21K0689/21K0689-p03/src/main/java/ru/mirea/practice/task4/Rand.java, students/21K0689/21K0689-p03/src/main/java/ru/mirea/practice/task5/Wrappers.java, students/21K0689/21K0689-p03/src/main/java/ru/mirea/practice/task6/Converter.java, students/21K0689/21K0689-p03/src/main/java/ru/mirea/practice/task7/Shop.java, students/21K0689/21K0689-p03/src/main/java/ru/mirea/practice/task8/Employee.java, students/21K0689/21K0689-p03/src/main/java/ru/mirea/practice/task8/Report.java, students/21K0689/pom.xml
Проверьте, пожалуйста, практическую работу
=> Третья практическая работа

students/21K0709/21K0709-p08/pom.xml, students/21K0709/21K0709-p08/src/main/java/ru/mirea/practice/s21k0709/task1/Naturalnumbers.java, students/21K0709/21K0709-p08/src/main/java/ru/mirea/practice/s21k0709/task1/Tester.java, students/21K0709/21K0709-p08/src/main/java/ru/mirea/practice/s21k0709/task2/Naturalnumbers.java, students/21K0709/21K0709-p08/src/main/java/ru/mirea/practice/s21k0709/task2/Tester.java, students/21K0709/21K0709-p08/src/main/java/ru/mirea/practice/s21k0709/task3/SumNum.java, students/21K0709/21K0709-p08/src/main/java/ru/mirea/practice/s21k0709/task3/Tester.java, students/21K0709/21K0709-p09/pom.xml, students/21K0709/21K0709-p09/src/main/java/ru/mirea/practice/s21k0709/task1/Student.java, students/21K0709/21K0709-p09/src/main/java/ru/mirea/practice/s21k0709/task1/Tester.java, students/21K0709/21K0709-p09/src/main/java/ru/mirea/practice/s21k0709/task2/SortingStudents.java, students/21K0709/21K0709-p09/src/main/java/ru/mirea/practice/s21k0709/task2/Student.java, students/21K0709/21K0709-p09/src/main/java/ru/mirea/practice/s21k0709/task2/Tester.java, students/21K0709/21K0709-p09/src/main/java/ru/mirea/practice/s21k0709/task3/MergeSort.java, students/21K0709/21K0709-p09/src/main/java/ru/mirea/practice/s21k0709/task3/Student.java, students/21K0709/21K0709-p09/src/main/java/ru/mirea/practice/s21k0709/task3/Tester.java, students/21K0709/pom.xml
Проверьте пожалуйста 8 и 9 практическую работу Турчанинова Даниила (КВБО-03-21)
=> Практические работы 8 и 9

students/21K0689/21K0689-p04/pom.xml, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task1/Seasons.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task1/Test.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task2/Atelier.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task2/Clothes.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task2/Main.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task2/MenClothing.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task2/Pants.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task2/Size.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task2/Skirt.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task2/TShirt.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task2/Tie.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task2/WomenClothing.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task3/App.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task3/Cart.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task3/Catalog.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task3/Product.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task3/User.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task4/Computer.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task4/Memory.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task4/Monitor.java, students/21K0689/21K0689-p04/src/main/java/ru/mirea/practice/task4/Processor.java, students/21K0689/pom.xml
Проверьте, пожалуйста, четвертую практическую работу
=> Четвертая практическая работа

students/21K0602/21K0602-p27/pom.xml, students/21K0602/21K0602-p27/src/main/java/ru/mirea/practice/task/HashTab.java, students/21K0602/21K0602-p27/src/main/java/ru/mirea/practice/task/Test.java, students/21K0602/pom.xml
Проверьте пожалуйста практические работы
=> Практические работы Давыдов Дениса КВБО-03-21

pom.xml, students/21K0710/21K0710-p11/pom.xml, students/21K0710/21K0710-p11/src/main/java/ru/mirea/workeleven/task2/Main.java, students/21K0710/21K0710-p11/src/main/java/ru/mirea/workeleven/task3/Student.java, students/21K0710/21K0710-p13/pom.xml, students/21K0710/21K0710-p13/src/main/java/ru/mirea/workthirteen/task4/Main.java, students/21K0710/21K0710-p13/src/main/java/ru/mirea/workthirteen/task4/Shirt.java, students/21K0710/21K0710-p13/src/main/java/ru/mirea/workthirteen/task5/Main.java, students/21K0710/21K0710-p14/pom.xml, students/21K0710/21K0710-p14/src/main/java/ru/mirea/workfourteen/task2/Main.java, students/21K0710/21K0710-p14/src/main/java/ru/mirea/workfourteen/task5/Main.java, students/21K0710/21K0710-p14/src/main/java/ru/mirea/workfourteen/task6/Main.java, students/21K0710/21K0710-p18/pom.xml, students/21K0710/21K0710-p18/src/main/java/ru/mirea/workeighteen/task3/Main.java, students/21K0710/21K0710-p18/src/main/java/ru/mirea/workeighteen/task4/Main.java, students/21K0710/21K0710-p18/src/main/java/ru/mirea/workeighteen/task7/Main.java, students/21K0710/21K0710-p19/pom.xml, students/21K0710/21K0710-p19/src/main/java/ru/mirea/worknineteen/task1/Main.java, students/21K0710/21K0710-p19/src/main/java/ru/mirea/worknineteen/task1/User.java, students/21K0710/21K0710-p19/src/main/java/ru/mirea/worknineteen/task1/WrongInnException.java, students/21K0710/21K0710-p19/src/main/java/ru/mirea/worknineteen/task2/Addition.java, students/21K0710/21K0710-p19/src/main/java/ru/mirea/worknineteen/task2/Main.java, students/21K0710/21K0710-p19/src/main/java/ru/mirea/worknineteen/task2/Student.java, students/21K0710/21K0710-p19/src/main/java/ru/mirea/worknineteen/task2/StudentNotFoundException.java, students/21K0710/pom.xml
проверьте пожалуйста 11-14 практические
=> Практические работы 11-19

students/21K0602/21K0602-p28/pom.xml, students/21K0602/21K0602-p28/src/main/java/ru/mirea/practice/task1/Main.java, students/21K0602/21K0602-p28/src/main/java/ru/mirea/practice/task2/Main.java, students/21K0602/21K0602-p28/src/main/java/ru/mirea/practice/task3/Main.java, students/21K0602/21K0602-p29/pom.xml, students/21K0602/21K0602-p29/src/main/java/ru/mirea/practice/task1/Main.java, students/21K0602/21K0602-p30/pom.xml, students/21K0602/21K0602-p30/src/main/java/ru/mirea/practice/task1/Main.java, students/21K0602/21K0602-p30/src/main/java/ru/mirea/practice/task1/Tree.java, students/21K0602/21K0602-p30/src/main/java/ru/mirea/practice/task2/Huffman.java, students/21K0602/21K0602-p30/src/main/java/ru/mirea/practice/task2/Main.java, students/21K0602/21K0602-p30/src/main/java/ru/mirea/practice/task2/Tree.java, students/21K0602/21K0602-p32/pom.xml, students/21K0602/21K0602-p32/src/main/java/ru/mirea/practice/task1/JonsTrot.java, students/21K0602/21K0602-p32/src/main/java/ru/mirea/practice/task1/Main.java, students/21K0602/pom.xml
Проверьте пожалуйста практические работы
=> Практические работы Давыдов Денис КВБО-03-21

students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program1/Circle.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program1/Rectangle.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program1/Shape.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program1/Square.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program1/Tester.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program2/Phone.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program2/Tester.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program7/Pupil.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program7/Schoolchild.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program7/Student.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program7/Tester.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program8/Circle.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program8/Rectangle.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program8/Shape.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program8/Square.java, students/21K0628/21K0628-p04.1/src/main/java/ru/mirea/practice/program8/Tester.java, students/21K0628/21K0628-p05/pom.xml, students/21K0628/pom.xml
Практическая работа №4.1 (1, 2, 7, 8)
=> Практические работа 4.1, Ким Инесса

students/21K0710/21K0710-p20/pom.xml, students/21K0710/21K0710-p20/src/main/java/ru/mirea/worktwenty/Animal.java, students/21K0710/21K0710-p20/src/main/java/ru/mirea/worktwenty/GenericBox.java, students/21K0710/21K0710-p22/pom.xml, students/21K0710/21K0710-p22/src/main/java/ru/mirea/worktwentytwo/Main.java, students/21K0710/21K0710-p22/src/main/java/ru/mirea/worktwentytwo/RpnCalc.java, students/21K0710/21K0710-p23/pom.xml, students/21K0710/21K0710-p23/src/main/java/ru/mirea/worktwentythree/task1/ArrayQueue.java, students/21K0710/21K0710-p23/src/main/java/ru/mirea/worktwentythree/task1/ArrayQueueAdt.java, students/21K0710/21K0710-p23/src/main/java/ru/mirea/worktwentythree/task1/ArrayQueueModule.java, students/21K0710/21K0710-p23/src/main/java/ru/mirea/worktwentythree/task2/AbstractQueue.java, students/21K0710/21K0710-p23/src/main/java/ru/mirea/worktwentythree/task2/ArrayQueue.java, students/21K0710/21K0710-p23/src/main/java/ru/mirea/worktwentythree/task2/LinkedQueue.java, students/21K0710/21K0710-p23/src/main/java/ru/mirea/worktwentythree/task2/Main.java, students/21K0710/21K0710-p23/src/main/java/ru/mirea/worktwentythree/task2/Node.java, students/21K0710/21K0710-p24/pom.xml, students/21K0710/21K0710-p24/src/main/java/ru/mirea/worktwentyfour/task1/Complex.java, students/21K0710/21K0710-p24/src/main/java/ru/mirea/worktwentyfour/task1/ComplexAbstractFactory.java, students/21K0710/21K0710-p24/src/main/java/ru/mirea/worktwentyfour/task1/ConcreteFactory.java, students/21K0710/21K0710-p24/src/main/java/ru/mirea/worktwentyfour/task2/AbstractChairFactory.java, students/21K0710/21K0710-p24/src/main/java/ru/mirea/worktwentyfour/task2/Chair.java, students/21K0710/21K0710-p24/src/main/java/ru/mirea/worktwentyfour/task2/ChairFactory.java, students/21K0710/21K0710-p24/src/main/java/ru/mirea/worktwentyfour/task2/Client.java, students/21K0710/21K0710-p24/src/main/java/ru/mirea/worktwentyfour/task2/FunctionalChair.java, students/21K0710/21K0710-p24/src/main/java/ru/mirea/worktwentyfour/task2/MagicChair.java, students/21K0710/21K0710-p24/src/main/java/ru/mirea/worktwentyfour/task2/VictorianChair.java, students/21K0710/pom.xml
=> Практические работы 20-24

students/21K0628/21K0628-p06/pom.xml, students/21K0628/21K0628-p06/src/main/java/ru/mirea/practice/program1/Movable.java, students/21K0628/21K0628-p06/src/main/java/ru/mirea/practice/program1/MovableCircle.java, students/21K0628/21K0628-p06/src/main/java/ru/mirea/practice/program1/MovablePoint.java, students/21K0628/21K0628-p06/src/main/java/ru/mirea/practice/program2/Animals.java, students/21K0628/21K0628-p06/src/main/java/ru/mirea/practice/program2/Nameable.java, students/21K0628/21K0628-p06/src/main/java/ru/mirea/practice/program2/Planets.java, students/21K0628/21K0628-p06/src/main/java/ru/mirea/practice/program2/Tester.java, students/21K0628/21K0628-p06/src/main/java/ru/mirea/practice/program6to9/Book.java, students/21K0628/21K0628-p06/src/main/java/ru/mirea/practice/program6to9/Printable.java, students/21K0628/21K0628-p06/src/main/java/ru/mirea/practice/program6to9/Shop.java, students/21K0628/21K0628-p06/src/main/java/ru/mirea/practice/program6to9/Tester.java, students/21K0628/21K0628-p07/pom.xml, students/21K0628/21K0628-p07/src/main/java/ru/mirea/practice/program4/MathCalculable.java, students/21K0628/21K0628-p07/src/main/java/ru/mirea/practice/program4/MathFunc.java, students/21K0628/21K0628-p07/src/main/java/ru/mirea/practice/program4/Tester.java, students/21K0628/21K0628-p07/src/main/java/ru/mirea/practice/program5to6/ProcessStrings.java, students/21K0628/21K0628-p07/src/main/java/ru/mirea/practice/program5to6/Strings.java, students/21K0628/21K0628-p07/src/main/java/ru/mirea/practice/program5to6/Tester.java, students/21K0628/21K0628-p07/src/main/java/ru/mirea/practice/program7to8/Book.java, students/21K0628/21K0628-p07/src/main/java/ru/mirea/practice/program7to8/Magazine.java, students/21K0628/21K0628-p07/src/main/java/ru/mirea/practice/program7to8/Printable.java, students/21K0628/21K0628-p07/src/main/java/ru/mirea/practice/program7to8/Tester.java, students/21K0628/pom.xml
Практическая работа 6 (1, 2, 6-9)
Практическая работа 7 (4, 5-6, 7-8)
=> Практические работы 6 и 7, Ким Инесса

students/21K0613/21K0613-p02/src/main/java/ru/mirea/practice/task1/Author.java, students/21K0613/21K0613-p02/src/main/java/ru/mirea/practice/task1/TestAuthor.java, students/21K0613/21K0613-p02/src/main/java/ru/mirea/practice/task2/Ball.java, students/21K0613/21K0613-p02/src/main/java/ru/mirea/practice/task2/TestBall.java, students/21K0613/21K0613-p02/src/main/java/ru/mirea/practice/task3/Circle.java, students/21K0613/21K0613-p02/src/main/java/ru/mirea/practice/task3/Point.java, students/21K0613/21K0613-p02/src/main/java/ru/mirea/practice/task3/Tester.java, students/21K0613/21K0613-p02/src/main/java/ru/mirea/practice/task8/StringSwap.java
=> практическая 2

students/21K0628/21K0628-p08/pom.xml, students/21K0628/21K0628-p08/src/main/java/ru/mirea/practice/program10/Reversenumber.java, students/21K0628/21K0628-p08/src/main/java/ru/mirea/practice/program11/CountOne.java, students/21K0628/21K0628-p08/src/main/java/ru/mirea/practice/program12/Oddnumber.java, students/21K0628/21K0628-p09/pom.xml, students/21K0628/21K0628-p09/src/main/java/ru/mirea/practice/program1/Student.java, students/21K0628/21K0628-p09/src/main/java/ru/mirea/practice/program1/Tester.java, students/21K0628/21K0628-p09/src/main/java/ru/mirea/practice/program2/SortingStudentBygpa.java, students/21K0628/21K0628-p09/src/main/java/ru/mirea/practice/program2/Tester.java, students/21K0628/pom.xml
=> Практические работы 8 и 9, Ким Инесса

students/21K0613/21K0613-p03/pom.xml, students/21K0613/21K0613-p03/src/main/java/ru/mirea/practice/formation/task1/Converter.java, students/21K0613/21K0613-p03/src/main/java/ru/mirea/practice/formation/task2/ShopApp.java, students/21K0613/21K0613-p03/src/main/java/ru/mirea/practice/formation/task3/Employee.java, students/21K0613/21K0613-p03/src/main/java/ru/mirea/practice/formation/task3/Main.java, students/21K0613/21K0613-p03/src/main/java/ru/mirea/practice/formation/task3/Report.java, students/21K0613/21K0613-p03/src/main/java/ru/mirea/practice/javashell/task1/Task1.java, students/21K0613/21K0613-p03/src/main/java/ru/mirea/practice/javashell/task1/task1.java, students/21K0613/21K0613-p03/src/main/java/ru/mirea/practice/mathrandom/task1/Task1.java, students/21K0613/21K0613-p03/src/main/java/ru/mirea/practice/mathrandom/task3/Task3.java, students/21K0613/pom.xml
=> третья практическая

students/21K0647/21K0647-p07/pom.xml, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt23/Movable.java, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt23/MovablePoint.java, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt23/MovableRectangle.java, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt23/Tester.java, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt4/MathCalculable.java, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt4/MathFunc.java, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt56/ProcessString.java, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt56/Tester.java, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt56/WorkString.java, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt78/Book.java, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt78/Magazine.java, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt78/Printable.java, students/21K0647/21K0647-p07/src/main/java/ru/mirea/practice/s21k0647/punkt78/Tester.java, students/21K0647/21K0647-p08/pom.xml, students/21K0647/21K0647-p08/src/main/java/ru/mirea/practice/s21k0647/Punkt1.java, students/21K0647/21K0647-p08/src/main/java/ru/mirea/practice/s21k0647/Punkt16.java, students/21K0647/21K0647-p08/src/main/java/ru/mirea/practice/s21k0647/Punkt17.java, students/21K0647/21K0647-p09/pom.xml, students/21K0647/21K0647-p09/src/main/java/ru/mirea/practice/s21k0647/punkt1/Student.java, students/21K0647/21K0647-p09/src/main/java/ru/mirea/practice/s21k0647/punkt1/Tester.java, students/21K0647/21K0647-p09/src/main/java/ru/mirea/practice/s21k0647/punkt2/SortingStudentsbygpa.java, students/21K0647/21K0647-p09/src/main/java/ru/mirea/practice/s21k0647/punkt2/Tester.java, students/21K0647/21K0647-p09/src/main/java/ru/mirea/practice/s21k0647/punkt3/Tester.java, students/21K0647/21K0647-p09/src/main/java/ru/mirea/practice/s21k0647/punkt4/Comparable.java, students/21K0647/21K0647-p09/src/main/java/ru/mirea/practice/s21k0647/punkt4/Tester.java, students/21K0647/pom.xml
Проверьте пожалуйста практическую работу №7 Лаврентьевой Карины (КВБО-03-21)
=> Добавлена пракическая работа №7

students/21K0613/21K0613-p03/src/main/java/ru/mirea/practice/formation/task2/ShopApp.java, students/21K0613/21K0613-p03/src/main/java/ru/mirea/practice/formation/task3/Main.java, students/21K0613/21K0613-p04/pom.xml, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task1/Main.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task1/Season.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task2/Atelier.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task2/Clothes.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task2/MenClothing.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task2/Pants.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task2/Sizes.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task2/Skirt.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task2/TShirt.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task2/Tie.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task2/WomenClothing.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task4/Brand.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task4/Computer.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task4/Memory.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task4/Monitor.java, students/21K0613/21K0613-p04/src/main/java/ru/mirea/practice/task4/Processor.java, students/21K0613/pom.xml
=> Практика 4

students/21K0589/21K0589-p08/pom.xml, students/21K0589/21K0589-p08/src/main/java/ru/mirea/practice/NumberReversed.java, students/21K0589/21K0589-p08/src/main/java/ru/mirea/practice/Palindrome.java, students/21K0589/21K0589-p08/src/main/java/ru/mirea/practice/Second.java, students/21K0589/pom.xml
=> 8 добавил!

students/21K0709/21K0709-p24/pom.xml, students/21K0709/21K0709-p24/src/main/java/ru/mirea/practice/s21k0709/task1/Complex.java, students/21K0709/21K0709-p24/src/main/java/ru/mirea/practice/s21k0709/task1/ComplexAbstractFactory.java, students/21K0709/21K0709-p24/src/main/java/ru/mirea/practice/s21k0709/task1/ConcreteFactory.java, students/21K0709/21K0709-p24/src/main/java/ru/mirea/practice/s21k0709/task1/Tester.java, students/21K0709/21K0709-p24/src/main/java/ru/mirea/practice/s21k0709/task2/AbstractChairFactory.java, students/21K0709/21K0709-p24/src/main/java/ru/mirea/practice/s21k0709/task2/Chair.java, students/21K0709/21K0709-p24/src/main/java/ru/mirea/practice/s21k0709/task2/ChairFactory.java, students/21K0709/21K0709-p24/src/main/java/ru/mirea/practice/s21k0709/task2/Client.java, students/21K0709/21K0709-p24/src/main/java/ru/mirea/practice/s21k0709/task2/FunctionalChair.java, students/21K0709/21K0709-p24/src/main/java/ru/mirea/practice/s21k0709/task2/MagicChair.java, students/21K0709/21K0709-p24/src/main/java/ru/mirea/practice/s21k0709/task2/Tester.java, students/21K0709/21K0709-p24/src/main/java/ru/mirea/practice/s21k0709/task2/VictorianChair.java, students/21K0709/21K0709-p25/pom.xml, students/21K0709/21K0709-p25/src/main/java/ru/mirea/practice/s21k0709/task1/Tester.java, students/21K0709/21K0709-p25/src/main/java/ru/mirea/practice/s21k0709/task2/Tester.java, students/21K0709/21K0709-p25/src/main/java/ru/mirea/practice/s21k0709/task3/Price.java, students/21K0709/21K0709-p26/pom.xml, students/21K0709/21K0709-p26/src/main/java/ru/mirea/practice/s21k0709/task1/Inverse.java, students/21K0709/21K0709-p26/src/main/java/ru/mirea/practice/s21k0709/task2to3/IteratorList.java, students/21K0709/21K0709-p26/src/main/java/ru/mirea/practice/s21k0709/task2to3/Node.java, students/21K0709/21K0709-p26/src/main/java/ru/mirea/practice/s21k0709/task2to3/Tester.java, students/21K0709/21K0709-p27/pom.xml, students/21K0709/21K0709-p27/src/main/java/ru/mirea/practice/s21k0709/HashTab.java, students/21K0709/21K0709-p27/src/main/java/ru/mirea/practice/s21k0709/Tester.java, students/21K0709/21K0709-p28/pom.xml, students/21K0709/21K0709-p28/src/main/java/ru/mirea/practice/s21k0709/task1/Tester.java, students/21K0709/21K0709-p28/src/main/java/ru/mirea/practice/s21k0709/task2/Tester.java, students/21K0709/21K0709-p28/src/main/java/ru/mirea/practice/s21k0709/task3/Tester.java, students/21K0709/pom.xml
Проверьте, пожалуйста, практические работы 24-28 Турчанинова Даниила (КВБО-03-21)
=> Практические работы 24-28

students/21K0623/21K0623-p27/pom.xml, students/21K0623/21K0623-p27/src/main/java/ru/mirea/practice/solutiontask1/Hashtab.java, students/21K0623/21K0623-p27/src/main/java/ru/mirea/practice/solutiontask1/Main.java, students/21K0623/21K0623-p27/src/main/java/ru/mirea/practice/solutiontask1/Node.java, students/21K0623/21K0623-p28/pom.xml, students/21K0623/21K0623-p28/src/main/java/ru/mirea/practice/solutiontask1/Main.java, students/21K0623/21K0623-p28/src/main/java/ru/mirea/practice/solutiontask2/Main.java, students/21K0623/21K0623-p28/src/main/java/ru/mirea/practice/solutiontask2/Maps.java, students/21K0623/21K0623-p28/src/main/java/ru/mirea/practice/solutiontask3/Main.java, students/21K0623/21K0623-p29/pom.xml, students/21K0623/21K0623-p29/src/main/java/ru/mirea/practice/solutiontask1/Solution.java, students/21K0623/21K0623-p30/pom.xml, students/21K0623/21K0623-p30/src/main/java/ru/mirea/practice/solutiontask1/Tree.java, students/21K0623/21K0623-p30/src/main/java/ru/mirea/practice/solutiontask2/Huffman.java, students/21K0623/21K0623-p30/src/main/java/ru/mirea/practice/solutiontask2/Main.java, students/21K0623/21K0623-p30/src/main/java/ru/mirea/practice/solutiontask2/Tree.java, students/21K0623/21K0623-p32/pom.xml, students/21K0623/21K0623-p32/src/main/java/ru/mirea/practice/solutiontask1/Trotter.java, students/21K0623/pom.xml
Проверьте пжл. Карпов Максим КВБО-02-21
=> Добавлены практические работы 27-32
